### ISSUE TITLE
Error compilation Virtualbox guest

### ISSUE THREAD

**Issue by 0pc0deFR** [subgraph/subgraph-os-issues#167]
I would install virtualbox guest 4.3.36 but doesn't work:

Uninstalling modules from DKMS
Attempting to install using DKMS

Creating symlink /var/lib/dkms/vboxguest/4.3.36/source ->
                 /usr/src/vboxguest-4.3.36

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make -j4 KERNELRELEASE=4.5.7-grsec-amd64 -C /lib/modules/4.5.7-grsec-amd64/build M=/var/lib/dkms/vboxguest/4.3.36/build....(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.5.7-grsec-amd64 (x86_64)
Consult /var/lib/dkms/vboxguest/4.3.36/build/make.log for more information.
Failed to install using DKMS, attempting to install without
grep: /lib/modules/4.5.7-grsec-amd64/build/include/linux/version.h: Aucun fichier ou dossier de ce type
make KBUILD_VERBOSE=1 CONFIG_MODULE_SIG= -C /lib/modules/4.5.7-grsec-amd64/build SUBDIRS=/tmp/vbox.0 SRCROOT=/tmp/vbox.0 modules
++ dirname ./scripts/gcc-plugin.sh
- srctree=./scripts
  ++ gcc -print-file-name=plugin
- gccplugins_dir=/usr/lib/gcc/x86_64-linux-gnu/5/plugin
  ++ g++ -E -x c++ - -o /dev/null -I./scripts/gcc-plugins -I/usr/lib/gcc/x86_64-linux-gnu/5/plugin/include
- plugincc='In file included from <stdin>:1:0:
  ./scripts/gcc-plugins/gcc-common.h:4:22: fatal error: bversion.h: Aucun fichier ou dossier de ce type
  compilation terminated.'
- '[' 1 -ne 0 ']'
- exit 1
  scripts/Makefile.gcc-plugins:61: warning, your gcc installation does not support plugins, perhaps the necessary headers are missing?
  scripts/Makefile.gcc-plugins:65: PAX_MEMORY_STACKLEAK and other features will be less secure
  Makefile:672: Cannot use CONFIG_CC_STACKPROTECTOR_REGULAR: -fstack-protector not supported by compiler
  test -e include/generated/autoconf.h -a -e include/config/auto.conf || (        \
  echo >&2;                           \
  echo >&2 "  ERROR: Kernel configuration is invalid.";       \
  echo >&2 "         include/generated/autoconf.h or include/config/auto.conf are missing.";\
  echo >&2 "         Run 'make oldconfig && make prepare' on kernel src to fix it.";  \
  echo >&2 ;                          \
  /bin/false)
  mkdir -p /tmp/vbox.0/.tmp_versions ; rm -f /tmp/vbox.0/.tmp_versions/*
  make -f ./scripts/Makefile.build obj=/tmp/vbox.0
  gcc -Wp,-MD,/tmp/vbox.0/.VBoxGuest-linux.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-linux-gnu/5/include -I./arch/x86/include -Iarch/x86/include/generated/uapi -Iarch/x86/include/generated  -Iinclude -I./arch/x86/include/uapi -Iarch/x86/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -maccumulate-outgoing-args -ffreestanding -DCONFIG_X86_X32_ABI -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -fno-delete-null-pointer-checks -O2 --param=allow-store-data-races=0 -fplugin=./scripts/gcc-plugins/constify_plugin.so -fplugin=./scripts/gcc-plugins/kernexec_plugin.so -fplugin=./scripts/gcc-plugins/colorize_plugin.so -fplugin=./scripts/gcc-plugins/size_overflow_plugin/size_overflow_plugin.so -fplugin=./scripts/gcc-plugins/latent_entropy_plugin.so -fplugin=./scripts/gcc-plugins/initify_plugin.so -fplugin=./scripts/gcc-plugins/rap_plugin/rap_plugin.so -DCONSTIFY_PLUGIN -DKERNEXEC_PLUGIN -fplugin-arg-kernexec_plugin-method="bts" -DSIZE_OVERFLOW_PLUGIN -DLATENT_ENTROPY_PLUGIN -DINITIFY_PLUGIN -DRAP_PLUGIN -fplugin-arg-rap_plugin-check=call -fplugin-arg-rap_plugin-hash=abs-finish -fstack-protector -fomit-frame-pointer -g -DCC_HAVE_ASM_GOTO -Wno-declaration-after-statement -include /tmp/vbox.0/include/VBox/VBoxGuestMangling.h -I/lib/modules/4.5.7-grsec-amd64/build/include -I/tmp/vbox.0/ -I/tmp/vbox.0/include -I/tmp/vbox.0/r0drv/linux -I/tmp/vbox.0/vboxguest/ -I/tmp/vbox.0/vboxguest/include -I/tmp/vbox.0/vboxguest/r0drv/linux -D__KERNEL__ -DMODULE -DVBOX -DRT_OS_LINUX -DIN_RING0 -DIN_RT_R0 -DIN_GUEST -DIN_GUEST_R0 -DIN_MODULE -DRT_WITH_VBOX -DVBGL_VBOXGUEST -DVBOX_WITH_HGCM -DRT_ARCH_AMD64 -DVBOX_WITH_64_BITS_GUESTS  -DMODULE  -D"KBUILD_STR(s)=#s" -D"KBUILD_BASENAME=KBUILD_STR(VBoxGuest_linux)"  -D"KBUILD_MODNAME=KBUILD_STR(vboxguest)" -c -o /tmp/vbox.0/.tmp_VBoxGuest-linux.o /tmp/vbox.0/VBoxGuest-linux.c
  cc1: error: cannot load plugin ./scripts/gcc-plugins/constify_plugin.so
  ./scripts/gcc-plugins/constify_plugin.so: undefined symbol: _ZN8opt_pass4gateEv
  cc1: error: cannot load plugin ./scripts/gcc-plugins/colorize_plugin.so
  ./scripts/gcc-plugins/colorize_plugin.so: undefined symbol: _ZN8opt_pass4gateEv
  cc1: error: cannot load plugin ./scripts/gcc-plugins/rap_plugin/rap_plugin.so
  ./scripts/gcc-plugins/rap_plugin/rap_plugin.so: undefined symbol: _ZN8opt_pass4gateEv
  cc1: error: cannot load plugin ./scripts/gcc-plugins/initify_plugin.so
  ./scripts/gcc-plugins/initify_plugin.so: undefined symbol: _ZN8opt_pass4gateEv
  cc1: error: cannot load plugin ./scripts/gcc-plugins/kernexec_plugin.so
  ./scripts/gcc-plugins/kernexec_plugin.so: undefined symbol: _ZN8opt_pass4gateEv
  cc1: error: cannot load plugin ./scripts/gcc-plugins/size_overflow_plugin/size_overflow_plugin.so
  ./scripts/gcc-plugins/size_overflow_plugin/size_overflow_plugin.so: undefined symbol: _ZN8opt_pass4gateEv
  cc1: error: cannot load plugin ./scripts/gcc-plugins/latent_entropy_plugin.so
  ./scripts/gcc-plugins/latent_entropy_plugin.so: undefined symbol: _ZN8opt_pass4gateEv
  scripts/Makefile.build:258 : la recette pour la cible « /tmp/vbox.0/VBoxGuest-linux.o » a échouée
  make[2]: **\* [/tmp/vbox.0/VBoxGuest-linux.o] Erreur 1
  Makefile:1409 : la recette pour la cible « _module_/tmp/vbox.0 » a échouée
  make[1]: **\* [_module_/tmp/vbox.0] Erreur 2
  /tmp/vbox.0/Makefile.include.footer:79 : la recette pour la cible « vboxguest » a échouée
  make: **\* [vboxguest] Erreur 2
  Creating user for the Guest Additions.
  Creating udev rule for the Guest Additions kernel module.

**Comment by whatisgravity** [comment]
Have you just tried libvirt with gnome-boxes? Virtual box has some components that are useful but are compiled commercial licensed code.

**Comment by xSmurf** [comment]
Should be corrected with recent kernel releases.

See also: https://github.com/subgraph/sgos_handbook/blob/master/05_features_and_advanced_usage_09_virtualmachines.md
